name: Publish Markdown to Confluence

on: workflow_dispatch  # bouton Manuel dans Github Actions

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
      - name: Publish Markdown to Confluence
        uses: TTengs/MarkdownToConfluence@v3
        with:
          configFile: .confluence.json
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
