name: Hello-test
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello word
        run: echo "Bonjour tout le monde"
  goodbaye:
    runs-on: ubuntu-latest
    steps:
      - name: Good baye
        run: echo "Goodbaye"

  TerraformInit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: TFE initialization
        run: terrform init
