name: Publish Markdown to Confluence

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish@v1
        with:
          configFile: confluence.json
        env:
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
